https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process#Example

https://dkenefake.github.io/blog/Orthoginalization

In [23]:
import numpy as np

def projection(u: np.array, v: np.array) -> np.array:
    """
    Returns the projection of vector v onto vector u
    """
    assert u.shape == v.shape, "Vectors must have the same shape"
    proj = np.dot(u, v) / np.dot(u, u) * u
    return proj

projection(np.array([1, 2, 0]), np.array([2, 0, 0]))

array([0.4, 0.8, 0. ])

In [26]:
def gram_schmidt(vectors: np.array) -> np.array:
    """
    Takes an array of input vectors and performs Gram-Schmidt orthogonalization
    to produce an orthonormal basis
    """
    # Make a copy of the input vectors that is all zeros
    output = np.zeros(vectors.shape)
    output[0] = vectors[0]

    for i in range(1, vectors.shape[0]):
        v = vectors[i]
        for j in range(i):
            u = output[j]
            v = v - projection(u, vectors[i])
        output[i] = v
    
    return output

test = gram_schmidt(np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1], [2, 3, 4]]))
test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [32]:
def zero_counter(matrix: np.array) -> int:
    """
    Returns the number of rows which are all zeros
    """
    return np.sum(np.all(matrix == 0, axis=1)), np.shape(matrix)[0]

zero_counter(test)

(np.int64(1), 4)

In [37]:
# Generate a random numpy array of shape (10, 3)
random_array = np.random.randint(0, 10, (10, 3))
print(random_array)
test2 = gram_schmidt(random_array)
print(test2)
zero_counter(test2)

[[9 8 9]
 [7 8 3]
 [9 7 6]
 [5 8 4]
 [4 3 3]
 [3 9 7]
 [9 0 1]
 [6 8 5]
 [6 0 2]
 [4 7 2]]
[[ 9.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 8.67256637e-01  2.54867257e+00 -3.13274336e+00]
 [ 1.04564315e+00 -7.84232365e-01 -3.48547718e-01]
 [ 1.77635684e-15 -3.55271368e-15  2.77555756e-16]
 [ 3.04761905e-01 -6.09523810e-01  4.76190476e-02]
 [ 5.53547133e+00 -1.10709427e+01  8.64917396e-01]
 [-5.46705539e+00  1.09341108e+01 -8.54227405e-01]
 [ 7.33916424e+00 -1.46783285e+01  1.14674441e+00]
 [-6.28182702e+00  1.25636540e+01 -9.81535471e-01]
 [ 1.15685131e+01 -2.31370262e+01  1.80758017e+00]]


(np.int64(0), 10)

Need to modify this to adapt to floating point stuff

In [44]:
def modifiedGramSchmidt(vectors: np.array) -> np.array:
    """
    Takes an array of input vectors and performs Gram-Schmidt orthogonalization
    to produce an orthonormal basis
    More resistant to floating point drama but takes longer to run
    """
    # Make a copy of the input vectors that is all zeros
    output = np.zeros(vectors.shape)
    near_output = output
    near_output[0] = vectors[0]

    for i in range(1, vectors.shape[0]):
        v = vectors[i]
        for j in range(i):
            u = output[j]
            v = v - projection(u, vectors[i])
        near_output[i] = v
    
    output[0] = near_output[0]
    for i in range(1, vectors.shape[0]):
        output[i] = near_output[i]
        for j in range(i):
            output[i] = output[i] - projection(output[j], near_output[i])
        output[i] = output[i]

    return output

random_array = np.random.randint(5, size=(10, 3))
print(random_array)
test3 = modifiedGramSchmidt(random_array)
print(test3)
# Now outputs zeros and NaNs

def zero_nan_counter(matrix: np.array) -> int:
    """
    Returns the number of rows which are all zeros or contain NaNs
    """
    return np.sum(np.all(np.isnan(matrix) | (matrix == 0), axis=1)), np.shape(matrix)

zero_nan_counter(test3)


[[0 0 3]
 [3 0 2]
 [2 2 3]
 [2 0 0]
 [4 2 2]
 [4 4 0]
 [3 4 1]
 [3 3 2]
 [1 0 2]
 [2 0 1]]
[[ 0.  0.  3.]
 [ 3.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  0.]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]
 [nan nan nan]]


C:\Users\hd15639\AppData\Local\Temp\ipykernel_24436\3740485388.py:8: RuntimeWarning: invalid value encountered in scalar divide
  proj = np.dot(u, v) / np.dot(u, u) * u


(np.int64(7), (10, 3))

https://dkenefake.github.io/blog/Orthoginalization

Now to modify the above process so it produces vectors which are nearly orthogonal